### ISSUE TITLE
Telnet

### ISSUE THREAD

**Issue by seivanov** [lowenware/AISL#2]
После обращения telnetom перестает отвечать.

Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
а
а
Connection closed by foreign host.

Listening 0.0.0.0:8000
127.0.0.1:34360 - connected
127.0.0.1:34360 - Begin GET: /
Home Page!
Content-Type: text/html
Content-Length: 81
127.0.0.1:34360 - disconnected
127.0.0.1:34366 - connected
127.0.0.1:34366 - disconnected
127.0.0.1:34388 - connected
127.0.0.1:34388 - disconnected

**Comment by voxelias** [comment]
Будет решено в ходе предстоящего рефакторинга парсера

**Comment by voxelias** [comment]
FIxed in 1.0.0
